#version: "3.8"
#
#services:
#  telegrambot:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Test
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1Rajas1234
#    depends_on:
#      - mysql  # Keep it simple without condition for now
#
#  mysql:
#    image: mysql:8.0
#    platform: linux/amd64  # Ensures compatibility for Mac M1/M2
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 1Rajas1234
#      MYSQL_DATABASE: Test
#    ports:
#      - "3306:3306"  # Change host port to avoid conflict with local MySQL
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      retries: 5
#      start_period: 10s
#      timeout: 5s
